import { useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { Link, Route, Routes, useLocation, useParams, useSearchParams } from 'react-router-dom'
import { EmptyState, MaterialCard, SearchBox, SubjectCard } from './components'
import { categoryNames, type Material, type Subject } from './domain/types'
import { platform } from './platform'
import { isExternalHttpUrl } from './platform/links'
import { staticMaterialsRepository as repository } from './repositories/materials-repository'

function useCatalog() {
  const [data, setData] = useState<{ subjects: Subject[]; materials: Material[] }>({ subjects: [], materials: [] })
  useEffect(() => { void Promise.all([repository.getSubjects(), repository.getMaterials()]).then(([subjects, materials]) => setData({ subjects, materials })) }, [])
  return data
}
function Layout({ children }: { children: ReactNode }) {
  const location = useLocation()
  return <div className="app"><header><Link className="brand" to="/" aria-label="Student Hub — главная"><span>SH</span>Student Hub</Link><nav aria-label="Основная навигация"><Link to="/">Каталог</Link><Link to="/search">Поиск</Link></nav></header><main key={location.pathname}>{children}</main><footer>Student Hub · Материалы открываются на Яндекс.Диске</footer></div>
}
function Home() {
  const { subjects, materials } = useCatalog(); const newest = [...materials].sort((a, b) => b.addedAt.localeCompare(a.addedAt)).slice(0, 3)
  return <><section className="hero"><p className="eyebrow">Учебные материалы в одном месте</p><h1>Учиться проще, когда всё под рукой.</h1><p>Находите лекции, лабораторные и методички за пару секунд.</p><SearchBox /></section><section><div className="section-title"><div><p className="eyebrow">Навигация</p><h2>Выберите семестр</h2></div></div><div className="semester-grid">{[1, 2, 3, 4].map((semester) => <Link key={semester} to={`/semester/${semester}`}>{semester}<small>семестр</small></Link>)}</div></section><section><div className="section-title"><div><p className="eyebrow">Предметы</p><h2>Популярное сейчас</h2></div><Link to="/semester/3">Все предметы →</Link></div><div className="card-grid">{subjects.map((subject) => <SubjectCard key={subject.id} subject={subject} count={materials.filter((item) => item.subjectId === subject.id).length} />)}</div></section><section><div className="section-title"><div><p className="eyebrow">Обновления</p><h2>Недавно добавлено</h2></div></div><div className="card-grid">{newest.map((material) => <MaterialCard key={material.id} material={material} subject={subjects.find((item) => item.id === material.subjectId)!} />)}</div></section></>
}
function SemesterPage() { const { id } = useParams(); const { subjects, materials } = useCatalog(); const semester = Number(id); if (!Number.isInteger(semester) || semester < 1) return <EmptyState title="Семестр не найден">Проверьте адрес страницы.</EmptyState>; const filtered = subjects.filter((subject) => subject.semester === semester); return <><p className="breadcrumb"><Link to="/">Главная</Link> / {semester} семестр</p><h1>{semester} семестр</h1>{filtered.length ? <div className="card-grid">{filtered.map((subject) => <SubjectCard key={subject.id} subject={subject} count={materials.filter((item) => item.subjectId === subject.id).length} />)}</div> : <EmptyState title="Пока пусто">Материалы для этого семестра ещё не добавлены.</EmptyState>}</> }
function SubjectPage() { const { id, category } = useParams(); const { subjects, materials } = useCatalog(); const subject = subjects.find((item) => item.id === id); if (!subject) return <EmptyState title="Предмет не найден">Возможно, ссылка устарела.</EmptyState>; const filtered = materials.filter((item) => item.subjectId === id && (!category || item.category === category)); return <><p className="breadcrumb"><Link to="/">Главная</Link> / <Link to={`/semester/${subject.semester}`}>{subject.semester} семестр</Link></p><h1>{subject.title}</h1><p className="lead">{subject.description}</p><div className="filters" aria-label="Категории материалов"><Link className={!category ? 'active' : ''} to={`/subject/${id}`}>Все</Link>{Array.from(new Set(materials.filter((item) => item.subjectId === id).map((item) => item.category))).map((key) => <Link key={key} className={category === key ? 'active' : ''} to={`/subject/${id}/${key}`}>{categoryNames[key]}</Link>)}</div>{filtered.length ? <div className="material-list">{filtered.map((material) => <MaterialCard key={material.id} material={material} subject={subject} />)}</div> : <EmptyState title="В этой категории пока нет материалов">Посмотрите все материалы предмета.</EmptyState>}</> }
function MaterialPage() { const { id } = useParams(); const { subjects, materials } = useCatalog(); const material = materials.find((item) => item.id === id); const subject = subjects.find((item) => item.id === material?.subjectId); if (!material || !subject) return <EmptyState title="Материал не найден">Проверьте ссылку или вернитесь в каталог.</EmptyState>; const safeUrl = isExternalHttpUrl(material.url) ? material.url : null; return <article className="material-detail"><p className="breadcrumb"><Link to={`/subject/${subject.id}`}>{subject.title}</Link> / {categoryNames[material.category]}</p><span className="tag">{categoryNames[material.category]}</span><h1>{material.title}</h1>{material.description && <p className="lead">{material.description}</p>}<dl><div><dt>Предмет</dt><dd>{subject.title}</dd></div><div><dt>Добавлено</dt><dd>{new Intl.DateTimeFormat('ru-RU', { dateStyle: 'long' }).format(new Date(material.addedAt))}</dd></div></dl>{safeUrl ? <><button className="button" onClick={() => { platform.haptic('medium'); platform.openLink(safeUrl) }}>Открыть на Яндекс.Диске <span aria-hidden="true">↗</span></button><a className="plain-link" href={safeUrl} target="_blank" rel="noreferrer">Открыть в новой вкладке</a></> : <p role="alert">Ссылка на материал недоступна. Обратитесь к администратору каталога.</p>}</article> }
function SearchPage() { const [params] = useSearchParams(); const query = params.get('q') ?? ''; const { subjects, materials } = useCatalog(); const results = useMemo(() => { const term = query.trim().toLocaleLowerCase('ru'); if (!term) return []; return materials.filter((m) => [m.title, m.category, m.description ?? '', subjects.find((s) => s.id === m.subjectId)?.title ?? '', ...m.keywords].some((value) => value.toLocaleLowerCase('ru').includes(term))) }, [materials, query, subjects]); return <><h1>Поиск</h1><SearchBox initial={query} />{query && <p className="result-count">{results.length ? `Найдено: ${results.length}` : 'Ничего не найдено'}</p>}{results.length > 0 ? <div className="material-list">{results.map((m) => <MaterialCard key={m.id} material={m} subject={subjects.find((s) => s.id === m.subjectId)!} />)}</div> : query ? <EmptyState title="Попробуйте другой запрос">Ищите по предмету, названию или ключевому слову.</EmptyState> : <p className="lead">Введите название материала, предмет или тему.</p>}</> }
function NotFound() { return <EmptyState title="Страница не найдена">Такого адреса в Student Hub нет.</EmptyState> }
export default function App() { return <Layout><Routes><Route path="/" element={<Home />} /><Route path="/semester/:id" element={<SemesterPage />} /><Route path="/subject/:id" element={<SubjectPage />} /><Route path="/subject/:id/:category" element={<SubjectPage />} /><Route path="/material/:id" element={<MaterialPage />} /><Route path="/search" element={<SearchPage />} /><Route path="*" element={<NotFound />} /></Routes></Layout> }
